apiVersion: kaptain.org/1.15
kind: docker-build-dockerfile

spec:
  global:
    release:
      versioning:
        maxParts: '4'
        strategy: file-pattern-match
        patternType: custom
        source:
          subPath: src/docker
          fileName: Dockerfile
          pattern: '^ARG BUSYBOX_VERSION=([0-9]+\.[0-9]+\.[0-9]+)$'
          prefixParts: '3'
  main:
    quality:
      branches:
        blockSlashes: true
      commits:
        blockConventional: true
    docker:
      platform: linux/amd64,linux/arm64
      dockerfile:
        squash: 'no'
        subPathLinuxAmd64: src/docker
        subPathLinuxArm64: src/docker
